services:
  f5tts:
    image: f5tts-gpu
    build:
      context: .
      dockerfile: Dockerfile.gpu
    container_name: f5tts-gpu-api
    ports:
      - "8012:8012"
    restart: "no"
    environment:
      - TZ=Europe/Paris
      - DEVICE=cuda
      - DEFAULT_VOICE=default
      - F5TTS_MODEL=F5TTS_v1_Base
    volumes:
      - ./voices:/app/voices
      - f5tts-cache:/root/.cache/huggingface
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

volumes:
  f5tts-cache:
