services:
  fishspeech:
    image: fishspeech-gpu
    build:
      context: .
      dockerfile: Dockerfile.gpu
    ports:
      - "8033:8033"
    restart: "no"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
